services:
  app-yolo-live:
    image: ghcr.io/amperecomputingai/yolo-live-demo:1.2.3
    network_mode: host
    ipc: host
    environment:
      FLASK_RUN_HOST: ${FLASK_RUN_HOST:-0.0.0.0}
      FLASK_RUN_PORT: ${FLASK_RUN_PORT:-5000}
      NUM_THREADS: ${NUM_THREADS:-32}
      VIDEO_SRC: ${VIDEO_SRC:-''}
